### ISSUE TITLE
插件设置

### ISSUE THREAD

**Issue by Marveliu** [nutzam/nutzboot-maven-plugin#3]
希望可优化插件，提供设置功能，例如在nutzboot:shade支持一下功能：

1. 最终文件名称
2. 文件输出路径
...

**Comment by ywjno** [comment]
貌似这些是在项目的 pom.xml 文件里面设置的

**Comment by wendal** [comment]
分别是 project.build.directory 和  finalName

**Comment by wendal** [comment]
因为nutzboot:shade是继承maven的shade插件
